

const vallejoModelColorNames = [
  "White", "Off White", "Ivory", "Light Flesh", "Basic Skin Tone", "Sunny Skin Tone", "Flat Flesh", "Dark Flesh",
  "Salmon Rose", "Beige Red", "Brown Rose", "Red", "Carmine Red", "Red Violet", "Old Rose", "Dark Rose",
  "Golden Yellow", "Bright Orange", "Clear Orange", "Lemon Yellow", "Yellow Ochre", "Orange Red", "Scarlet",
  "Flat Red", "Vermilion", "Amaranth Red", "Magenta", "Purple", "Violet", "Blue Violet", "Sky Blue", "Azure",
  "Flat Blue", "Prussian Blue", "Dark Blue", "Royal Blue", "Turquoise", "Blue Green", "Deep Sky Blue", "Light Blue",
  "Green Blue", "Refractive Green", "Flat Green", "Military Green", "US Dark Green", "Camouflage Olive Green",
  "Olive Green", "Intermediate Green", "Yellow Green", "Lime Green", "Park Green Flat", "Bright Green", "Dark Green",
  "German Cam. Bright Green", "German Cam. Dark Green", "Russian Uniform WWII", "Field Green", "Green Brown",
  "Khaki", "Khaki Grey", "Brown Sand", "Cork Brown", "Flat Earth", "Chocolate Brown", "Flat Brown", "Mahogany Brown",
  "Burnt Umber", "Burnt Sienna", "Orange Brown", "Red Leather", "Tan Earth", "US Field Drab", "Cam. Medium Brown",
  "Cam. Light Brown", "Cam. Pale Brown", "Cam. Orange Ochre", "Cam. Yellow Ochre", "Cam. Light Ochre", "Cam. Pale Sand",
  "Cam. Light Sand", "Cam. Pale Sand Yellow", "Cam. Light Yellow", "Cam. Pale Yellow", "Cam. Light Yellow Ochre",
  "Cam. Pale Yellow Ochre", "Cam. Light Ochre Yellow", "Cam. Pale Ochre Yellow", "Cam. Light Brown Yellow",
  "Cam. Pale Brown Yellow", "Cam. Light Tan", "Cam. Pale Tan", "Cam. Light Flesh", "Cam. Pale Flesh", "Cam. Light Skin",
  "Cam. Pale Skin", "Cam. Light Beige", "Cam. Pale Beige", "Cam. Light Ivory", "Cam. Pale Ivory", "Cam. Light White",
  "Cam. Pale White", "Neutral Grey", "Black Grey", "Basalt Grey", "Medium Sea Grey", "Light Grey", "Pale Grey",
  "Cold Grey", "Warm Grey", "Stone Grey", "Ash Grey", "London Grey", "German Grey", "Dark Grey", "Charcoal Grey",
  "Black", "German Cam. Black Brown", "German Cam. Medium Brown", "German Cam. Beige", "German Cam. Pale Brown",
  "German Cam. Light Brown", "German Cam. Ochre", "German Cam. Yellow", "German Cam. Light Yellow", "German Cam. Sand",
  "German Cam. Pale Sand", "German Cam. Light Sand", "German Cam. Pale Yellow", "German Cam. Light Yellow Ochre",
  "German Cam. Pale Yellow Ochre", "German Cam. Light Ochre Yellow", "German Cam. Pale Ochre Yellow",
  "German Cam. Light Brown Yellow", "German Cam. Pale Brown Yellow", "German Cam. Light Tan", "German Cam. Pale Tan",
  "German Cam. Light Flesh", "German Cam. Pale Flesh", "German Cam. Light Skin", "German Cam. Pale Skin",
  "German Cam. Light Beige", "German Cam. Pale Beige", "German Cam. Light Ivory", "German Cam. Pale Ivory",
  "German Cam. Light White", "German Cam. Pale White", "US Olive Drab", "US Dark Green", "US Field Drab",
  "US Tan Earth", "US Khaki", "US Sand", "US Light Sand", "US Pale Sand", "US Light Yellow", "US Pale Yellow",
  "US Light Ochre", "US Pale Ochre", "US Light Brown", "US Pale Brown", "US Light Tan", "US Pale Tan",
  "US Light Flesh", "US Pale Flesh", "US Light Skin", "US Pale Skin", "US Light Beige", "US Pale Beige",
  "US Light Ivory", "US Pale Ivory", "US Light White", "US Pale White", "British Uniform", "English Uniform",
  "Russian Uniform", "Japanese Uniform", "Italian Uniform", "French Uniform", "Spanish Uniform", "Austrian Uniform",
  "German Uniform", "Polish Uniform", "Dutch Uniform", "Belgian Uniform", "Norwegian Uniform", "Swedish Uniform",
  "Finnish Uniform", "Swiss Uniform", "Greek Uniform", "Turkish Uniform", "Yugoslav Uniform", "Hungarian Uniform",
  "Romanian Uniform", "Bulgarian Uniform", "Czech Uniform", "Slovak Uniform", "Portuguese Uniform", "Irish Uniform",
  "Danish Uniform", "Luxembourg Uniform", "Icelandic Uniform", "Canadian Uniform", "Australian Uniform",
  "New Zealand Uniform", "South African Uniform", "Indian Uniform", "Pakistani Uniform", "Bangladeshi Uniform",
  "Sri Lankan Uniform", "Nepalese Uniform", "Bhutanese Uniform", "Maldivian Uniform", "Afghan Uniform",
  "Iranian Uniform", "Iraqi Uniform", "Syrian Uniform", "Lebanese Uniform", "Jordanian Uniform", "Israeli Uniform",
  "Egyptian Uniform", "Libyan Uniform", "Tunisian Uniform", "Algerian Uniform", "Moroccan Uniform", "Sudanese Uniform",
  "Ethiopian Uniform", "Somali Uniform", "Kenyan Uniform", "Ugandan Uniform", "Rwandan Uniform", "Burundian Uniform",
  "Tanzanian Uniform", "Zambian Uniform", "Zimbabwean Uniform", "Malawian Uniform", "Mozambican Uniform",
  "Angolan Uniform", "Namibian Uniform", "Botswanan Uniform", "South Sudanese Uniform", "Chadian Uniform",
  "Nigerien Uniform", "Malian Uniform", "Senegalese Uniform", "Gambian Uniform", "Guinean Uniform", "Bissau-Guinean Uniform",
  "Sierra Leonean Uniform", "Liberian Uniform", "Ivorian Uniform", "Ghanaian Uniform", "Togolese Uniform",
  "Beninese Uniform", "Cameroonian Uniform", "Central African Uniform", "Congolese Uniform", "Gabonese Uniform",
  "Equatorial Guinean Uniform", "São Toméan Uniform", "Cape Verdean Uniform", "Comorian Uniform", "Mauritian Uniform",
  "Seychellois Uniform", "Madagascan Uniform"
];